version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  book-writer-easy.cyrhades.fr:
    image: anssi/fcsc2024-pwn-book-writer-easy:latest
    ports:
      - ${PORT_SSH}:4000
